all: createTask.applescript getTaskData.applescript updateTask.applescript
	osacompile -o createTask.scpt createTask.applescript
	osacompile -o getTaskData.scpt getTaskData.applescript
	osacompile -o updateTask.scpt updateTask.applescript